### ISSUE TITLE
make fast

### ISSUE THREAD

**Issue by Spixa** [KasraIDK/Simple-Calculator#2]
u can make more fast and readable if move line `System.out.println("result " + result);` after the switch and also `return;` in `default:`

**Comment by Spixa** [comment]
جاست دو ایت

**Comment by KasraIDK** [comment]
bruh that looks like shit what how do I make it look good

**Comment by Spixa** [comment]
> like so?
> ` switch (operationstr) {
>             case "Add", "+", "add" -> {
>                 double result = input1double + input2double;
>             }
>             case "Subtract", "-", "subtract" -> {
>                 double result = input1double - input2double;
>             }
>             case "Multiply", "*", "multiply" -> {
>                 double result = input1double * input2double;
>             }
>             case "Divide", "/", "divide" -> {
>                 double result = input1double / input2double;
>             }
>             default -> System.out.println("That operation is not supported, please try again.");
>         }
> System.out.println("Result: " + result);`

yes also return; in default

**Comment by Spixa** [comment]
Nw
